Update build wheels job to test the wheels (#56)
## Primary Changes
* Update build_wheels.yaml to test CUDA-QX wheels after building them.
* Update build_wheels.yaml to build CUDA-Q wheels rather than using
released PyPi CUDA-Q wheels. This was necessary because the current
0.9.1 CUDA-Q wheels have an ARM bug that were impacting our ability to
do testing. This was fixed in
https://github.com/NVIDIA/cuda-quantum/pull/2504, which has not been
released yet.
* Fix RPATH of decoder plugin example (thanks for the suggestion,
@melody-ren) to fix a wheel packaging problem where `auditwheel` as
duplicating (aka grafting) the `libcudaq-qec.so` file, causing
`extension_point` registration anomalies and decoder plugin lookup
failures.

## Secondary Changes
* In .github/actions/get-cudaq-version/action.yaml, skip `jq` install if
it is already installed
* Add get-cudaq-wheels action; currently only invoked on manually
commanded build_wheels.yaml workflow but we may decide to invoke this on
a per-PR basis in the future.
* Change retention period of all uploaded artifacts to 14 days
* Update `getCUDAQXLibraryPath` to work for both QEC and Solvers
* Change decoder-plugins path from a build-time constant (which will not
work for wheels) to use `getCUDAQXLibraryPath` instead.
* Change use of shared_ptr to unique_ptr in decoder plugin handling
* Move decoder plugin helper functions into namespaces rather than
global namespace
* Change cudaqx wheels to be depending on cuda-quantum >= 0.9 rather
than ~= 0.9.0 for better futureproofing of our released wheels

Sample run result w/ custom CUDA-Q wheels:
https://github.com/NVIDIA/cudaqx/actions/runs/12855925162
Sample run result w/ released PyPI CUDA-Q wheels:
https://github.com/NVIDIA/cudaqx/actions/runs/12856394702

---------

Signed-off-by: Ben Howe <bhowe@nvidia.com>

diff --git a/.github/workflows/build_wheels.yaml b/.github/workflows/build_wheels.yaml
--- a/.github/workflows/build_wheels.yaml
+++ b/.github/workflows/build_wheels.yaml
@@ -6,20 +6,32 @@ on:
       build_type:
         type: choice
         required: true
-        description: 'Build Type'
+        description: 'Build Type (ignored if using artifacts from prior run)'
         default: 'Release'
         options:
         - 'Release'
         - 'Debug'
-
+      cudaq_wheels:
+        type: choice
+        required: true
+        description: 'CUDA-Q wheel source (released version from PyPI or Custom built using .cudaq_version in repo)'
+        default: 'Custom'
+        options:
+        - 'Custom'
+        - 'PyPI'
+      artifacts_from_run:
+        type: string
+        description: Optional argument to take artifacts from a prior run of this workflow; facilitates rerunning a failed workflow without re-building the artifacts.
+        required: false
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 jobs:
-  linux-build:
-    name: Linux build
+  build-cudaqx-wheels:
+    name: Build CUDA-QX wheels
+    if: ${{ !inputs.artifacts_from_run }}
     runs-on: linux-${{ matrix.platform }}-cpu8
     # CUDAQ requires a highly specialized environment to build. Thus, it is much
     # easier to rely on their's devdeps images to do the building.
@@ -60,16 +72,186 @@ jobs:
 
       - name: Build CUDAQ toolchain
         run: |
-          .github/workflows/scripts/build_cudaq.sh 
+          .github/workflows/scripts/build_cudaq.sh ${{ matrix.python }}
 
-      - name: Build wheels
+      - name: Build CUDA-QX wheels
         run: |
           .github/workflows/scripts/build_wheels.sh \
               --cudaq-prefix $HOME/.cudaq \
-              --build-type ${{ inputs.build_type }}
+              --build-type ${{ inputs.build_type }} \
+              --python-version ${{ matrix.python }}
 
       - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
           name: wheels-py${{ matrix.python }}-${{ matrix.platform }}
           path: /wheels/**
+          retention-days: 14
+
+  # Building the CUDA-Q wheels must be done outside of a container context, so
+  # this is a separate job.
+  build-cudaq-wheels:
+    name: Build CUDA-Q wheels
+    if: ${{ !inputs.artifacts_from_run && inputs.cudaq_wheels == 'Custom'}}
+    strategy:
+      fail-fast: false
+      matrix:
+        platform: ['amd64', 'arm64']
+    # Use 32 CPUs rather than 8 (above) because we are only spawning one job per
+    # platform rather than one job per Python version per platform.
+    runs-on: ${{ startsWith(github.repository, 'NVIDIA/cudaqx') && format('linux-{0}-cpu32', matrix.platform) || 'ubuntu-latest' }}
+    permissions:
+      actions: write
+      contents: read
+      pull-requests: read
+    steps:
+      - name: Get code
+        uses: actions/checkout@v4
+        with:
+          set-safe-directory: true
+
+      - name: Get required CUDAQ version
+        id: get-cudaq-version
+        uses: ./.github/actions/get-cudaq-version
+
+      - name: Get CUDAQ wheels
+        uses: ./.github/actions/get-cudaq-wheels
+        with:
+          repo: ${{ steps.get-cudaq-version.outputs.repo }}
+          ref: ${{ steps.get-cudaq-version.outputs.ref }}
+          token: ${{ secrets.CUDAQ_ACCESS_TOKEN }}
+          save-build: true
+          platform: ${{ matrix.platform }}
+
+      - name: Upload CUDAQ wheels
+        uses: actions/upload-artifact@v4
+        with:
+          name: cudaq-wheels-${{ matrix.platform }}
+          path: /cudaq-wheels
+          retention-days: 14
+          if-no-files-found: error
+
+  test-cudaqx-wheels:
+    name: Test CUDA-QX wheels (CPU)
+    needs: [build-cudaqx-wheels, build-cudaq-wheels]
+    if: ${{ !failure() && !cancelled() }}
+    runs-on: linux-${{ matrix.platform }}-cpu4
+    container: ubuntu:22.04
+    permissions:
+      actions: write
+      contents: read
+    strategy:
+      fail-fast: false
+      matrix:
+        python: ['3.10', '3.11', '3.12']
+        platform: ['amd64', 'arm64']
+  
+    steps:
+      - name: Get code
+        uses: actions/checkout@v4
+        with:
+          set-safe-directory: true
+  
+      - name: Install Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python }}
+  
+      - name: Install requirements
+        run: |
+          bash .github/workflows/scripts/install_git_cli.sh
+          apt install -y --no-install-recommends libgfortran5 unzip
+  
+      - name: Download CUDA-Q wheels
+        if: ${{ inputs.cudaq_wheels == 'Custom' }}
+        uses: actions/download-artifact@v4
+        with:
+          name: cudaq-wheels-${{ matrix.platform }}
+          path: /cudaq-wheels
+          run-id: ${{ inputs.artifacts_from_run || github.run_id }}
+          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
+
+      - name: Download CUDA-QX wheels
+        uses: actions/download-artifact@v4
+        with:
+          name: wheels-py${{ matrix.python }}-${{ matrix.platform }}
+          path: /wheels
+          run-id: ${{ inputs.artifacts_from_run || github.run_id }}
+          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
+  
+      - name: Test wheels
+        run: |
+          ls /wheels
+          bash scripts/ci/test_wheels.sh ${{ matrix.python }}
+  
+  test-wheels-gpu:
+    name: Test CUDA-QX wheels (GPU)
+    needs: [build-cudaqx-wheels, build-cudaq-wheels]
+    if: ${{ !failure() && !cancelled() }}
+    runs-on: linux-${{ matrix.runner.arch }}-gpu-${{ matrix.runner.gpu }}-latest-1
+    container:
+      image: nvidia/cuda:12.0.0-base-ubuntu22.04
+      # Enable this if you want to collect core files. (You may might to enable
+      # Debug builds if you're doing this.)
+      #options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
+      env:
+        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
+    permissions:
+      actions: write
+      contents: read
+    strategy:
+      fail-fast: false
+      matrix:
+        runner: [
+          { arch: arm64, gpu: a100 },
+          { arch: amd64, gpu: v100 },
+        ]
+        python: ['3.10', '3.11', '3.12']
+  
+    steps:
+      - name: Get code
+        uses: actions/checkout@v4
+        with:
+          set-safe-directory: true
+  
+      - name: Install Python ${{ matrix.python }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python }}
+  
+      - name: Install requirements
+        run: |
+          bash .github/workflows/scripts/install_git_cli.sh
+          apt install -y --no-install-recommends libgfortran5 unzip
+          #echo 'core.%p' | tee /proc/sys/kernel/core_pattern
+          #echo "Running cat /proc/sys/kernel/core_pattern"
+          #cat /proc/sys/kernel/core_pattern
+  
+      - name: Download CUDA-Q wheels
+        if: ${{ inputs.cudaq_wheels == 'Custom' }}
+        uses: actions/download-artifact@v4
+        with:
+          name: cudaq-wheels-${{ matrix.runner.arch }}
+          path: /cudaq-wheels
+          run-id: ${{ inputs.artifacts_from_run || github.run_id }}
+          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
+
+      - name: Download CUDA-QX wheels
+        uses: actions/download-artifact@v4
+        with:
+          name: wheels-py${{ matrix.python }}-${{ matrix.runner.arch }}
+          path: /wheels
+          run-id: ${{ inputs.artifacts_from_run || github.run_id }}
+          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
+  
+      - name: Test wheels
+        run: |
+          ls /wheels
+          bash scripts/ci/test_wheels.sh ${{ matrix.python }}
+
+      # - name: Upload any core files
+      #   if: success() || failure()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: core-files-${{ matrix.python }}-arm64
+      #     path: core.*
